# Generated by Django 3.0.8 on 2021-10-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidadfecharegistro', models.DateField(auto_now_add=True)),
                ('especialidadfechamodificacion', models.DateField(auto_now_add=True)),
                ('especialidadnombre', models.CharField(max_length=50)),
                ('especialidadestado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('pwd', models.CharField(max_length=150)),
                ('Edad', models.IntegerField()),
                ('Genero', models.CharField(max_length=1)),
                ('Estado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacientefecharegistro', models.DateField(auto_now_add=True)),
                ('pacientefechamodificacion', models.DateField(auto_now_add=True)),
                ('pacientecedula', models.CharField(max_length=10)),
                ('pacienteapellido', models.CharField(max_length=30)),
                ('pacientenombre', models.CharField(max_length=30)),
                ('pacientedireccion', models.CharField(max_length=30)),
                ('pacienteestado', models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_creacion', models.CharField(max_length=15)),
                ('usuario_modificacion', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolnombre', models.CharField(max_length=50)),
                ('rolestado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorfecharegistro', models.DateField(auto_now_add=True)),
                ('doctorfechamodificacion', models.DateField(auto_now_add=True)),
                ('doctorcedula', models.CharField(max_length=10)),
                ('doctorregistro', models.CharField(max_length=10)),
                ('doctorapellido', models.CharField(max_length=30)),
                ('doctornombre', models.CharField(max_length=30)),
                ('doctordireccion', models.CharField(max_length=30)),
                ('doctorestado', models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', max_length=1)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='cita_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita_medicacodigo', models.CharField(max_length=10)),
                ('cita_medicaregistro', models.DateField(auto_now_add=True, null=True)),
                ('cita_medicamodificacion', models.DateField(auto_now_add=True, null=True)),
                ('cita_medicafecha', models.DateField()),
                ('cita_medicahora', models.TimeField()),
                ('cita_medicaestado', models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', max_length=1)),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.doctor')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.especialidad')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.paciente')),
            ],
        ),
    ]
