# Generated by Django 3.0.8 on 2021-10-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialidadestado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='ficha_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha_medica_registro', models.DateField(auto_now_add=True, null=True)),
                ('ficha_medica_modificacion', models.DateField(auto_now_add=True, null=True)),
                ('ficha_medica_codigo', models.IntegerField()),
                ('ficha_medica_diagnostico', models.CharField(max_length=150)),
                ('ficha_medica_tratamiento', models.CharField(max_length=150)),
                ('ficha_medica_estado', models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', max_length=1)),
                ('id_cita_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.cita_medica')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.doctor')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.especialidad')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencore.paciente')),
            ],
        ),
    ]
